# Numpy
**numpy** is a python library focused around efficient mathematical operations. By abusing caching, using vectorized operations and optimized C code, the numpy package is comparable to operations done in other compiled versions (e.g. C, Java, etc...).

Go over the tutorial in [this link](https://numpy.org/doc/stable/user/quickstart.html) to learn how to use numpy.

In [4]:
import numpy as np

arr = np.arange(0, 100).reshape(10, 10)
print(arr)

print(np.sum(arr, axis=0))
print(np.sum(arr, axis=1))

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
[450 460 470 480 490 500 510 520 530 540]
[ 45 145 245 345 445 545 645 745 845 945]


# Pandas

In [14]:
import pandas as pd

df = pd.read_csv('resources/got-character-deaths.csv')
print(df.columns)
print(df.head())
df.groupby('Book of Death').apply(lambda series: series['Nobility'].mean())

Index(['Name', 'Allegiances', 'Death Year', 'Book of Death', 'Death Chapter',
       'Book Intro Chapter', 'Gender', 'Nobility', 'GoT', 'CoK', 'SoS', 'FfC',
       'DwD'],
      dtype='object')
                      Name      Allegiances  Death Year  Book of Death  \
0           Addam Marbrand        Lannister         NaN            NaN   
1  Aegon Frey (Jinglebell)             None       299.0            3.0   
2          Aegon Targaryen  House Targaryen         NaN            NaN   
3            Adrack Humble    House Greyjoy       300.0            5.0   
4           Aemon Costayne        Lannister         NaN            NaN   

   Death Chapter  Book Intro Chapter  Gender  Nobility  GoT  CoK  SoS  FfC  \
0            NaN                56.0       1         1    1    1    1    1   
1           51.0                49.0       1         1    0    0    1    0   
2            NaN                 5.0       1         1    0    0    0    0   
3           20.0                20.0       1     

Book of Death
1.0    0.346939
2.0    0.356164
3.0    0.422680
4.0    0.481481
5.0    0.344262
dtype: float64